### ISSUE TITLE
Clean up display of more info modal

### ISSUE THREAD

**Issue by bryanmtl** [DynamoMTL/spree_log_viewer#1]
![screen shot 2014-01-22 at 8 28 00 am](https://f.cloud.github.com/assets/12205/1976981/ddc8277e-8391-11e3-8d6e-35508bcc4109.png)

**Comment by papayaah** [comment]
this is done - its going to look something like this now - http://d.pr/i/gARN but I'm unable to push. Can you give me push access please?

**Comment by bryanmtl** [comment]
Looking good @mickeyren! Push access coming up.
