### ISSUE TITLE
More info link is broken when multiple log entries exist

### ISSUE THREAD

**Issue by bryanmtl** [DynamoMTL/spree_log_viewer#2]
![screen shot 2014-01-22 at 8 27 53 am](https://f.cloud.github.com/assets/12205/1976989/f0891ab2-8391-11e3-8b1f-bbdee83720cd.png)

**Comment by nemy** [comment]
@bryanmtl what tool are you using for marking up screenshots?

**Comment by bryanmtl** [comment]
@nemy Just the built-in screen capture in Mavericks. You can then enable edit mode to add the fancy circles (thanks to @biancouver for pointing this out to me!).
