### ISSUE TITLE
"More Info" link is broken

### ISSUE THREAD

**Issue by bryanmtl** [DynamoMTL/spree_log_viewer#6]
@Rickytony  The following error is raised when clicking "More info":

`Uncaught TypeError: $(...).dialog is not a function`

Fixing this would give our CSR teams (SmartThings, Lola, ADay, Glossier, etc) a bit more visibility into the responses we receive from the gateway. 

Assigning this to you for whenver you have time. 

cc: @mickeyren

**Comment by papayaah** [comment]
@bryanmtl its fixed. i removed the dependency on jquery dialog and just show the `div` I just installed this on Lola.

**Comment by papayaah** [comment]
and updated the gem version on SmartThings

**Comment by bryanmtl** [comment]
Nice - thanks!
